#!/bin/bash

cd /workspaces/bouilloon.github.io/
git add -A
read -p "Nom du commit SOURCES: " sources
git commit -m "$sources"
git push

# Update static website by building sources
bundle exec jekyll build && cd ../static

# Copy built sources
cp -rf /workspaces/bouilloon.github.io/_site/* .
# Push to git
git add -A

read -p "Nom du commit SITE_STATIQUE: " static
git commit -m "$static"
git push
